# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GET_API' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'ObjectMapper', '~> 3.4'
	pod 'Alamofire', '~> 4.0'
  # Pods for GET_API

end

